Swift 3
theappbusiness/TABScrollingContentView pull request #3
Opened 2016-09-29 23:12 UTC by danielablg

2016-09-30 10:49 UTC, lucianomarisi requested changes
could the Gemfile and Gemfile.lock files go

2016-09-30 10:49 UTC, lucianomarisi commented on TABScrollingContentView.podspec
> +  s.platform	 = :ios, '10.0'
why has this changed to 10?

2016-09-30 10:50 UTC, lucianomarisi requested changes
could the Gemfile and Gemfile.lock files go?

2016-09-30 11:33 UTC, danielablg commented on TABScrollingContentView.podspec
> +  s.platform	 = :ios, '10.0'
I have reversed that in the latest commit

2016-10-03 08:43 UTC, samdods commented on README.md
> +addHorizontal(subviews:withMargins:horizontalSpacing:)
should be `add(horizontalSubviews:`

2016-10-03 08:43 UTC, samdods commented on README.md
> +addHorizontal(subviews:withMargins:horizontalSpacing:)
should be `add(horizontalSubviews:`

2016-10-03 08:43 UTC, samdods commented on README.md
> +addHorizontal(subviews:withMargins:horizontalSpacing:)
should be `add(horizontalSubviews:`

2016-10-03 09:30 UTC, samdods commented on Sources/ScrollingContentView.swift
> +    let constraint = NSLayoutConstraint(item: contentView, attribute: sourceAttribute, relatedBy: NSLayoutRelation.equal, toItem: targetView, attribute: targetAttribute, multiplier: 1, constant: 0)
could be `addConstraint(to:`

2016-10-03 09:30 UTC, samdods commented on Sources/ScrollingContentView.swift
> +    scrollView.backgroundColor = UIColor.clear
no need to change but just fyi you could use `= .clear` and `frame: .zero` for simplicity

2016-10-03 09:30 UTC, samdods commented on Sources/UIView+Subviews.swift
> +      addConstraints(fromSubiew: subview, previousView: previousView, margins: margins, verticalSpacing: verticalSpacing)
could be `addConstraints(from:`

2016-10-03 09:35 UTC, lucianomarisi approved these changes

2016-10-06 09:53 UTC, merged